apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
    - name: my-container
      image: my-image
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.5"
        limits:
          memory: "400Mi"
          cpu: "1"